name: Publish Docker image
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  page_build:
  release:
    types: 
      - created
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: endocker299/kubeflow-centraldashboard
          tag_with_ref: true
